version: 0.0
os: linux

files:
        - source: /
          destination: /home/ubuntu/MinimumTemp

permissions:
        - object: start.sh
          owner: ubuntu
          group: ubuntu
          mode: 755

hooks:
        ApplicationStart:
                - location: start.sh
                  timeout: 60
                  runas: ubuntu
